let dados = [
    {
        titulo: "Miragem",
        descricao: "Mirage é um dos mapas mais icônicos e populares de Counter-Strike (CS2), sendo amplamente jogado tanto em partidas casuais quanto em competições profissionais. Ambientado em uma região desértica de estilo marroquino, o mapa é conhecido por seu layout equilibrado que favorece tanto estratégias ofensivas quanto defensivas, oferecendo uma variedade de rotas e oportunidades táticas para ambos os lados.<br><br>Mirage tem dois bombsites (A e B), cada um com suas características estratégicas. O bombsite A é amplo e aberto, cercado por entradas como a 'rampa', o 'palácio' e o 'jungle', o que cria oportunidades para confrontos a longa distância e exige que os jogadores façam uso inteligente de granadas para se protegerem e avançarem. O bombsite B, por outro lado, é mais compacto e cercado por rotas estreitas, como o 'tapete' e a 'van', tornando-se um ponto de ataque intenso e de curta distância, onde a coordenação de equipe é essencial para executar rushes rápidos ou defesas sólidas.<br><br>O 'meio' em Mirage é um dos pontos-chave do mapa, sendo uma área de grande contestação entre os terroristas e contra-terroristas. Controlar o meio é crucial, pois ele oferece várias rotas alternativas para os bombsites, como o 'conector' para o A e a 'passarela' (short) para o B.<br><br>Mirage se destaca pela sua estrutura simples, mas com grande profundidade tática. Com a atualização para o CS2, Mirage recebeu aprimoramentos visuais, com detalhes mais refinados, melhor iluminação e texturas mais nítidas, que modernizam o mapa sem alterar sua jogabilidade clássica.<br><br>Em resumo, Mirage é um mapa que equilibra agressividade e estratégia, com espaços para tiroteios abertos e zonas de emboscada apertadas, criando um ambiente competitivo e dinâmico que mantém sua relevância desde as primeiras versões da série.",
        tags: "mirage, Mirage, MIRAGE, miragem, Miragem, MIRAGEM"
    },
    {
        titulo: "Vertigo",
        descricao: "O mapa Vertigo em Counter-Strike 2 (CS2) é uma recriação do icônico mapa da série, que mantém a essência do original com algumas atualizações visuais e mecânicas. Ambientado no topo de um arranha-céu em construção, Vertigo oferece um cenário de combate único com múltiplos andares e áreas de alto risco, exigindo que os jogadores estejam atentos aos espaços verticais e às bordas perigosas.<br><br>Com duas áreas de bombsite (A e B), o mapa é conhecido por seu layout compacto e dinâmico, promovendo combates intensos em corredores estreitos e plataformas elevadas. A entrada para o bombsite A está mais exposta, oferecendo linhas de visão longas e vulneráveis, enquanto o bombsite B é acessado por caminhos mais complexos, com várias rotas possíveis, encorajando a tática e o uso criativo de granadas.<br><br>Vertigo é um mapa onde o domínio dos timings é crucial, pois pequenos atrasos podem custar caro tanto para os terroristas quanto para os contra- terroristas. Além disso, o som desempenha um papel importante, já que o mapa é relativamente pequeno, facilitando a detecção de passos e movimentos inimigos. A verticalidade é uma característica central, com muitas oportunidades para saltos, flanqueios e controle de altura, o que faz com que jogadores habilidosos e que saibam usar bem o ambiente se destaquem.<br><br>A adaptação para o CS2 traz uma atualização visual impressionante, com melhorias na iluminação e nos detalhes da construção, tornando a experiência mais imersiva sem comprometer a jogabilidade clássica que os fãs amam.",
        tags: "vertigo, VERTIGO, Vertigo"
    },
    {
        titulo: "Nuke",
        descricao: "Nuke é um dos mapas mais distintos e táticos de Counter-Strike 2 (CS2), conhecido por sua complexa verticalidade e design multi-nível. Situado em uma instalação nuclear, o mapa oferece um cenário industrial onde o posicionamento e o controle do espaço são cruciais. O ambiente único de Nuke, com dois bombsites localizados em diferentes andares, desafia os jogadores a se adaptarem a combates em alturas diferentes, exigindo uma compreensão sólida do mapa e do uso de granadas.<br><br> Nuke é dividido em dois bombsites: o bombsite A, localizado no andar superior, e o bombsite B, no subterrâneo. O bombsite A é caracterizado por sua área aberta com várias plataformas elevadas, como o 'silo', 'hut' e 'heaven', que permitem posicionamentos estratégicos para os contra-terroristas. O bombsite B, por outro lado, é mais fechado e difícil de acessar, sendo frequentemente defendido por rotações rápidas e táticas de controle de espaço, com entradas principais pela 'ventilação' e pela 'rampa'.<br><br>Um dos aspectos mais marcantes de Nuke é sua verticalidade e as múltiplas rotas que conectam os diferentes níveis do mapa. Isso inclui o uso frequente da 'vent' para transições rápidas entre os bombsites e a 'rampa', que oferece um caminho crucial para os terroristas tentarem se infiltrar no bombsite B. Além disso, o exterior do mapa (outside) é uma área de grande disputa, onde os terroristas podem tentar atravessar a área aberta em direção ao bombsite B pelo subterrâneo, usando granadas de fumaça para cobrir a movimentação e evitar os atiradores de longa distância.<br><br> Nuke é notoriamente um mapa que favorece os contra-terroristas, devido à complexidade das rotas e à facilidade de defesa dos bombsites, mas equipes bem coordenadas podem usar estratégias de rotação rápida e controle de mapa para surpreender os adversários.<br><br>Com as atualizações no CS2, Nuke recebeu melhorias visuais, mantendo seu design clássico, mas com gráficos mais detalhados e efeitos de iluminação aprimorados, o que aumenta a imersão sem comprometer a jogabilidade que o define. A combinação de espaços fechados, áreas abertas e a necessidade de dominar diferentes níveis de altura faz de Nuke um dos mapas mais desafiadores e recompensadores para jogadores de Counter-Strike.",
        tags: "nuke, Nuke, NUKE"
    },
    {
        titulo: "Ancient",
        descricao: "Ancient é um mapa relativamente recente em Counter-Strike 2 (CS2), ambientado em uma antiga civilização mesoamericana, cercada por vegetação densa, ruínas e templos de pedra.<br><br>O mapa apresenta dois bombsites: A e B. O bombsite A é cercado por ruínas e rotas estreitas, oferecendo boas oportunidades para emboscadas e controlando ângulos apertados. A abordagem para esse site exige uma excelente coordenação de equipe e uso preciso de granadas para cobrir as muitas linhas de visão. O bombsite B, por outro lado, é mais aberto e rodeado por áreas com bastante vegetação, com uma entrada principal e um caminho mais estreito que passa por uma área conhecida como 'mid'. O controle de B frequentemente depende de quem domina o 'meio' do mapa, que serve como ponto de transição crucial entre as áreas.<br><br>O 'meio' em Ancient é uma das zonas mais disputadas, com uma série de caminhos interligados que permitem o flanqueio e a rotação rápida. Equipes que conseguem controlar o meio ganham um enorme poder estratégico, já que ele oferece acesso tanto ao bombsite A quanto ao B, além de proporcionar rotas de flanqueio para surpreender os adversários. Essa parte do mapa é composta por ruínas e áreas cobertas por vegetação densa, onde o uso de granadas de fumaça e molotovs pode bloquear ou forçar a movimentação dos inimigos.<br><br>Uma característica marcante de Ancient é sua vasta quantidade de cantos e locais para 'jiggle peeking' (espiar rapidamente) e o potencial de se esconder em áreas escuras e cobertas pela vegetação. Isso favorece tanto defensores quanto atacantes que buscam jogar de forma passiva, aguardando o avanço dos oponentes ou aproveitando o terreno para emboscar. O mapa também conta com vários 'boosts' e posições de vantagem elevadas, onde os jogadores podem obter ângulos inesperados sobre os adversários.<br><br>Apesar de ser um mapa relativamente novo em comparação com clássicos como Dust2 e Mirage, Ancient já conquistou seu espaço na rotação competitiva graças ao seu equilíbrio entre estratégias de controle de espaço e movimentação rápida, tornando-o um campo de batalha dinâmico e imprevisível.",
        tags: "ancient, anci, Ancient, ANCIENT"
    },
    {
        titulo: "Inferno",
        descricao: "Inferno é um dos mapas mais clássicos e icônicos de Counter-Strike 2 (CS2), conhecido por sua atmosfera em uma vila mediterrânea, com ruas estreitas, varandas e fachadas coloridas que criam um ambiente acolhedor, mas repleto de oportunidades táticas intensas.<br><br>O mapa é estruturado em torno de dois bombsites: A e B. O bombsite A é cercado por áreas estratégicas como o 'pit' e o 'site', além do corredor conhecido como 'apartamento' e a entrada principal chamada 'long'. Essas zonas proporcionam uma variedade de ângulos para combate e rotas de entrada que favorecem tanto os defensores quanto os atacantes. A defesa do bombsite A frequentemente se concentra em controlar a entrada pela 'longa' e impedir avanços rápidos por 'short' e 'apartamentos'.<br><br>O bombsite B, por sua vez, é defendido em uma área mais fechada, conhecida pela 'banana', um corredor estreito e curvo que conecta os terroristas ao site. Controlar a 'banana' é uma prioridade absoluta para ambos os times, já que ele é a principal rota de ataque para o B. O bombsite em si é compacto, com diversas coberturas e áreas para se esconder, como o 'coffins' e o 'dark', o que cria um ambiente de defesa forte, mas que pode ser rompido por um uso coordenado de granadas e rushes bem planejados.<br><br>Um aspecto central de Inferno é o controle do 'meio' (mid), uma área de grande importância estratégica que conecta o spawn terrorista aos dois bombsites. Dominar o meio permite cortar as rotações inimigas e oferecer novas rotas para ambos os sites. Jogadores costumam utilizar granadas de fumaça e molotovs para bloquear o avanço adversário e forçar reposicionamentos, criando um jogo tático baseado em paciência e timing.<br><br>Outro destaque de Inferno são suas posições elevadas, como as varandas nos apartamentos e a área de 'graveyard' no bombsite A, que oferecem ângulos de tiro elevados, permitindo que os jogadores se escondam ou ganhem vantagem visual sobre o adversário. <br><br>A combinação de áreas apertadas, caminhos largos e múltiplas rotas de entrada cria um equilíbrio perfeito entre agressividade e defesa, fazendo de Inferno um dos mapas mais amados e jogados na rotação competitiva de Counter-Strike.",
        tags: "inferno, INFERNO, Inferno, inf, INF, Inf"
    },
    {
        titulo: "Overpass",
        descricao: "Overpass é um dos mapas mais únicos e taticamente desafiadores em Counter-Strike 2 (CS2), com uma ambientação urbana moderna, situada em torno de um parque e uma área industrial próxima a um canal e uma estação de tratamento de água.<br><br>Com dois bombsites (A e B), Overpass se destaca pela clara divisão de espaços de combate. O bombsite A, localizado no topo de um viaduto, é uma área ampla e aberta, com várias entradas, como o banheiro e a longa. Ele oferece posições defensivas com linhas de visão longas, o que favorece o uso de rifles e AWPs, sendo um ponto estratégico para os contra-terroristas controlarem. O bombsite A também tem uma plataforma elevada, permitindo que os jogadores utilizem a verticalidade a seu favor. O controle do banheiro e da área da fonte é crucial para os terroristas, que podem utilizar essas rotas para avançar de forma estratégica e rápida.<br><br>O bombsite B, por outro lado, está situado perto do sistema de esgoto e é acessado por rotas estreitas, como o 'short' e a 'water'. É uma área mais compacta e muito perigosa para rushes rápidos, pois tanto os terroristas quanto os contra-terroristas precisam estar atentos às rotas de flanqueio que passam pelo túnel ou pela escada.<br><br>O meio de Overpass é uma das áreas mais cruciais do mapa, conectando tanto o bombsite A quanto o B. Controlar o meio dá uma enorme vantagem tática para os terroristas, já que eles podem manter as opções abertas para decidir qual bombsite atacar, dependendo de como os contra-terroristas estão distribuídos.<br><br>Visualmente, Overpass foi aprimorado no CS2 com detalhes mais ricos e uma iluminação natural que destaca a atmosfera urbana do mapa. As texturas renovadas e a estética mais vibrante tornam o cenário ainda mais imersivo, enquanto mantém intacta a jogabilidade que o tornou um dos mapas mais desafiadores e populares na rotação competitiva. A combinação de espaços amplos e confinados, com ênfase em controle de área e movimentação estratégica, faz de Overpass um mapa ideal para equipes que preferem táticas de jogo complexas e criativas.",
        tags: "overpass, OVERPASS, Overpass, over, Over"
    },
    {
        titulo: "Dust 2",
        descricao: "Dust2 é um dos mapas mais icônicos da série Counter-Strike e continua presente na nova versão do jogo, Counter-Strike 2 (CS2). Sua fama vem de seu layout simples e equilibrado, que oferece um bom nível de competitividade tanto para jogadores casuais quanto profissionais. O mapa se concentra em dois bombsites principais: o Bombsite A, que pode ser acessado pelos terroristas através da 'Longa' ou da 'Catwalk', e o Bombsite B, geralmente atacado via 'Túnel'. Essas duas rotas, juntamente com a importância estratégica do 'Meio' do mapa, fazem de Dust2 um campo de batalha dinâmico e desafiador.<br><br>No Counter-Strike 2, Dust2 recebeu uma atualização visual significativa graças à engine Source 2. As melhorias incluem texturas mais detalhadas, iluminação mais realista e um ambiente mais imersivo. Apesar das mudanças visuais, o layout do mapa permanece o mesmo, garantindo que jogadores veteranos ainda se sintam confortáveis ao navegar pelas áreas familiares. <br><br>A jogabilidade em Dust2 continua a exigir uma boa comunicação e coordenação entre os membros da equipe. Dominar áreas cruciais, como o meio, e fazer rotações eficazes entre os bombsites são estratégias essenciais para o sucesso. Granadas como smokes, flashes e molotovs também desempenham um papel vital na execução de ataques e na defesa dos pontos. Em CS2, essas dinâmicas táticas ficaram ainda mais complexas e interessantes, tornando Dust2 um mapa que continua relevante e emocionante no cenário competitivo.",
        tags: "dust2, DUST2, Dust2, Dust 2, DUST 2, dust 2"
    },
];